// Course data for BITS Pilani Second Semester 2025-26
// Data extracted exactly from "timetable 30 dec" PDF

export type SessionType = "lecture" | "tutorial" | "lab"

export type Remark =
  | "God"
  | "Demi-God"
  | "Highly Recommended"
  | "Recommended"
  | "Better"
  | "Good"
  | "Decent"
  | "Mediocre"
  | "Unknown"
  | "Avoid"
  | "Absolutely Avoid"
  | "Avoid at any cost"
  | "New (1 credit)"
  | "Both same"
  | "Lenient grading"
  | "Best"
  | "Horrendous"
  | "Prefer RS-led"
  | "Strict"
  | "Better for lectures"
  | "Preferred"
  | "TBA"
  | "Avoid (PUMA)"

export interface Session {
  section: string
  room: string
  days: string
  hours: string
  rating: number
  instructor: string
  remarks: Remark
  type: SessionType
}

export interface Course {
  id: string
  name: string
  code: string
  group: "A" | "B" | "common"
  lectures: Session[]
  tutorials: Session[]
  labs: Session[]
}

// Parse day codes: M=Monday, T=Tuesday, W=Wednesday, Th=Thursday, F=Friday, S=Saturday
export const dayMap: Record<string, string> = {
  M: "Monday",
  T: "Tuesday",
  W: "Wednesday",
  Th: "Thursday",
  F: "Friday",
  S: "Saturday",
}

// Hour slots (1-10)
export const hourSlots: Record<string, string> = {
  "1": "8:00-8:50",
  "2": "9:00-9:50",
  "3": "10:00-10:50",
  "4": "11:00-11:50",
  "5": "12:00-12:50",
  "6": "2:00-2:50",
  "7": "3:00-3:50",
  "8": "4:00-4:50",
  "9": "5:00-5:50",
  "10": "6:00-6:50",
}

export function getRemarkColor(remark: Remark): string {
  switch (remark) {
    case "God":
      return "text-yellow-400"
    case "Demi-God":
      return "text-amber-400"
    case "Highly Recommended":
      return "text-green-400"
    case "Recommended":
    case "Better":
    case "Good":
    case "Preferred":
      return "text-green-500"
    case "Decent":
    case "Mediocre":
      return "text-blue-400"
    case "Unknown":
    case "Both same":
    case "New (1 credit)":
    case "TBA":
      return "text-muted-foreground"
    case "Lenient grading":
    case "Prefer RS-led":
    case "Better for lectures":
    case "Best":
      return "text-emerald-400"
    case "Avoid":
    case "Avoid (PUMA)":
      return "text-orange-500"
    case "Absolutely Avoid":
    case "Avoid at any cost":
    case "Horrendous":
    case "Strict":
      return "text-red-500"
    default:
      return "text-muted-foreground"
  }
}

export function getRemarkOutline(remark: Remark): string {
  switch (remark) {
    default:
      return "border-border"
  }
}

export function getRemarkBg(remark: Remark): string {
  switch (remark) {
    case "God":
      return "bg-yellow-500/10 border-yellow-500/30"
    case "Demi-God":
      return "bg-amber-500/10 border-amber-500/30"
    case "Highly Recommended":
    case "Recommended":
    case "Better":
    case "Good":
    case "Preferred":
    case "Best":
      return "bg-green-500/10 border-green-500/30"
    case "Decent":
    case "Mediocre":
      return "bg-blue-500/10 border-blue-500/30"
    case "Lenient grading":
    case "Prefer RS-led":
    case "Better for lectures":
      return "bg-emerald-500/10 border-emerald-500/30"
    case "Avoid":
    case "Avoid (PUMA)":
      return "bg-orange-500/10 border-orange-500/30"
    case "Absolutely Avoid":
    case "Avoid at any cost":
    case "Horrendous":
    case "Strict":
      return "bg-red-500/10 border-red-500/30"
    default:
      return "bg-muted/50 border-border"
  }
}

// ============================================================
// EXACT DATA FROM PDF "timetable 30 dec"
// Only sections listed in the PDF are included
// ============================================================

export const courses: Course[] = [
  {
    id: "chem",
    name: "Fundamentals of Chemistry",
    code: "CHEM101",
    group: "A",
    lectures: [
      {
        section: "L1",
        room: "5105",
        days: "M W",
        hours: "2",
        rating: 8,
        instructor: "Saumi Ray",
        remarks: "Good",
        type: "lecture",
      },
      {
        section: "L2",
        room: "5105",
        days: "M W",
        hours: "4",
        rating: 7,
        instructor: "Anil Kumar",
        remarks: "Decent",
        type: "lecture",
      },
    ],
    tutorials: [
      {
        section: "T1",
        room: "6102",
        days: "F",
        hours: "1",
        rating: 7,
        instructor: "Anil Kumar",
        remarks: "Decent",
        type: "tutorial",
      },
      {
        section: "T2",
        room: "6162",
        days: "F",
        hours: "1",
        rating: 7,
        instructor: "Partha Sarathi Addy",
        remarks: "Decent",
        type: "tutorial",
      },
      {
        section: "T3",
        room: "6105",
        days: "F",
        hours: "1",
        rating: 8,
        instructor: "Satyajit Patra",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T4",
        room: "6109",
        days: "F",
        hours: "1",
        rating: 6,
        instructor: "Dalip Kumar",
        remarks: "Decent",
        type: "tutorial",
      },
      {
        section: "T5",
        room: "1219",
        days: "F",
        hours: "1",
        rating: 9.5,
        instructor: "Paritosh Shukla",
        remarks: "Highly Recommended",
        type: "tutorial",
      },
      {
        section: "T6",
        room: "1220",
        days: "F",
        hours: "1",
        rating: 3,
        instructor: "Ram Kinkar Roy",
        remarks: "Avoid",
        type: "tutorial",
      },
      {
        section: "T7",
        room: "1222",
        days: "F",
        hours: "1",
        rating: 5,
        instructor: "Ajay Kumar Sah",
        remarks: "Mediocre",
        type: "tutorial",
      },
      {
        section: "T8",
        room: "6161",
        days: "T",
        hours: "9",
        rating: 6,
        instructor: "Dalip Kumar",
        remarks: "Decent",
        type: "tutorial",
      },
      {
        section: "T9",
        room: "6162",
        days: "T",
        hours: "9",
        rating: 7,
        instructor: "Partha Sarathi Addy",
        remarks: "Decent",
        type: "tutorial",
      },
      {
        section: "T10",
        room: "6164",
        days: "T",
        hours: "9",
        rating: 8,
        instructor: "Satyajit Patra",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T11",
        room: "6105",
        days: "T",
        hours: "9",
        rating: 3,
        instructor: "Prashant Uday Manohar",
        remarks: "Avoid",
        type: "tutorial",
      },
      {
        section: "T12",
        room: "6109",
        days: "T",
        hours: "9",
        rating: 9.5,
        instructor: "Paritosh Shukla",
        remarks: "Highly Recommended",
        type: "tutorial",
      },
      {
        section: "T13",
        room: "1219",
        days: "T",
        hours: "9",
        rating: 0,
        instructor: "Vijy Kumar",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T14",
        room: "1220",
        days: "T",
        hours: "9",
        rating: 5,
        instructor: "Ajay Kumar Sah",
        remarks: "Mediocre",
        type: "tutorial",
      },
    ],
    labs: [
      {
        section: "P1",
        room: "3103",
        days: "F",
        hours: "1-2",
        rating: 8,
        instructor: "Bharti Khungar",
        remarks: "Recommended",
        type: "lab",
      },
      {
        section: "P2",
        room: "3103",
        days: "F",
        hours: "3-4",
        rating: 9.5,
        instructor: "Paritosh Shukla",
        remarks: "Highly Recommended",
        type: "lab",
      },
      {
        section: "P3",
        room: "3103",
        days: "F",
        hours: "6-7",
        rating: 4,
        instructor: "Inamur Rahaman Laskar",
        remarks: "Avoid",
        type: "lab",
      },
      {
        section: "P4",
        room: "3103",
        days: "S",
        hours: "1-2",
        rating: 7,
        instructor: "Partha Sarathi Addy",
        remarks: "Decent",
        type: "lab",
      },
      {
        section: "P5",
        room: "3103",
        days: "T",
        hours: "1-2",
        rating: 6.5,
        instructor: "Mrinmoyee Basu",
        remarks: "Decent",
        type: "lab",
      },
      {
        section: "P6",
        room: "3103",
        days: "T",
        hours: "3-4",
        rating: 9.5,
        instructor: "Paritosh Shukla",
        remarks: "Highly Recommended",
        type: "lab",
      },
      {
        section: "P7",
        room: "3103",
        days: "T",
        hours: "6-7",
        rating: 7,
        instructor: "Partha Sarathi Addy",
        remarks: "Decent",
        type: "lab",
      },
      {
        section: "P8",
        room: "3103",
        days: "Th",
        hours: "1-2",
        rating: 8,
        instructor: "Saumi Ray",
        remarks: "Recommended",
        type: "lab",
      },
      {
        section: "P9",
        room: "3103",
        days: "Th",
        hours: "3-4",
        rating: 0,
        instructor: "Vijy Kumar",
        remarks: "Unknown",
        type: "lab",
      },
      {
        section: "P10",
        room: "3103",
        days: "Th",
        hours: "6-7",
        rating: 4,
        instructor: "Inamur Rahaman Laskar",
        remarks: "Avoid",
        type: "lab",
      },
    ],
  },
  {
    id: "es",
    name: "Electrical Sciences",
    code: "ES101",
    group: "A",
    lectures: [
      {
        section: "L1",
        room: "5105",
        days: "M W Th",
        hours: "3,3,9",
        rating: 8,
        instructor: "Navneet Gupta",
        remarks: "Good",
        type: "lecture",
      },
      {
        section: "L2",
        room: "5105",
        days: "T Th F",
        hours: "2,2,2",
        rating: 9,
        instructor: "Praveen Kumar A.V.",
        remarks: "Better",
        type: "lecture",
      },
    ],
    tutorials: [
      {
        section: "T1",
        room: "1231",
        days: "F",
        hours: "7",
        rating: 0,
        instructor: "Abhijit Rameshwar Asati",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T2",
        room: "1202",
        days: "T",
        hours: "1",
        rating: 0,
        instructor: "Syed Mohammad Zafaruddin",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T3",
        room: "1201",
        days: "F",
        hours: "7",
        rating: 9,
        instructor: "Praveen Kumar A.V.",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T4",
        room: "1227",
        days: "F",
        hours: "7",
        rating: 0,
        instructor: "Neeraj Mishra",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T5",
        room: "6157",
        days: "F",
        hours: "7",
        rating: 7,
        instructor: "Bhavesh Chauhan",
        remarks: "Decent",
        type: "tutorial",
      },
      {
        section: "T6",
        room: "1231",
        days: "T",
        hours: "1",
        rating: 0,
        instructor: "Dinesh Rano",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T7",
        room: "1232",
        days: "T",
        hours: "1",
        rating: 7,
        instructor: "Pankaj Arora",
        remarks: "Decent",
        type: "tutorial",
      },
      {
        section: "T8",
        room: "1203",
        days: "T",
        hours: "1",
        rating: 9,
        instructor: "Arnab Hazra",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T9",
        room: "6153",
        days: "T",
        hours: "1",
        rating: 7,
        instructor: "Bhavesh Chauhan",
        remarks: "Decent",
        type: "tutorial",
      },
      {
        section: "T10",
        room: "1205",
        days: "T",
        hours: "1",
        rating: 0,
        instructor: "Satyendra Kumar Mourya",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T11",
        room: "1232",
        days: "F",
        hours: "7",
        rating: 3,
        instructor: "Karunesh KR Gupta",
        remarks: "Avoid",
        type: "tutorial",
      },
    ],
    labs: [],
  },
  {
    id: "oaw",
    name: "Oscillation And Waves",
    code: "PHY101",
    group: "A",
    lectures: [
      {
        section: "L1",
        room: "5102",
        days: "T Th",
        hours: "4,4",
        rating: 9,
        instructor: "Raj Kumar Gupta",
        remarks: "Preferred",
        type: "lecture",
      },
      {
        section: "L2",
        room: "5102",
        days: "T Th",
        hours: "6,6",
        rating: 6,
        instructor: "Anshuman Dalvi",
        remarks: "Decent",
        type: "lecture",
      },
    ],
    tutorials: [
      {
        section: "T1",
        room: "6157",
        days: "F",
        hours: "8",
        rating: 0,
        instructor: "Subhashis Gangopadhyay",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T2",
        room: "6158",
        days: "F",
        hours: "8",
        rating: 0,
        instructor: "Srijata Dey",
        remarks: "Absolutely Avoid",
        type: "tutorial",
      },
      {
        section: "T3",
        room: "6159",
        days: "F",
        hours: "8",
        rating: 0,
        instructor: "Rakesh Choubisa",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T4",
        room: "6160",
        days: "F",
        hours: "8",
        rating: 8,
        instructor: "Niladri Sarkar",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T5",
        room: "6161",
        days: "F",
        hours: "8",
        rating: 9,
        instructor: "Rishikesh Vaidya",
        remarks: "Demi-God",
        type: "tutorial",
      },
      {
        section: "T6",
        room: "6162",
        days: "F",
        hours: "8",
        rating: 8,
        instructor: "Debashis Bandyopadhyay",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T7",
        room: "6151",
        days: "F",
        hours: "8",
        rating: 8,
        instructor: "Aritra Banerjee",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T8",
        room: "6103",
        days: "F",
        hours: "8",
        rating: 2,
        instructor: "Sandipan Dutta",
        remarks: "Avoid",
        type: "tutorial",
      },
      {
        section: "T9",
        room: "6161",
        days: "Th",
        hours: "1",
        rating: 0,
        instructor: "Rakesh Choubisa",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T10",
        room: "6162",
        days: "Th",
        hours: "1",
        rating: 0,
        instructor: "Subhashis Gangopadhyay",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T11",
        room: "6156",
        days: "Th",
        hours: "1",
        rating: 0,
        instructor: "Tanmoy Mondal",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T12",
        room: "6163",
        days: "Th",
        hours: "1",
        rating: 9,
        instructor: "Tapomoy Guha Sarkar",
        remarks: "Demi-God",
        type: "tutorial",
      },
      {
        section: "T13",
        room: "6164",
        days: "Th",
        hours: "1",
        rating: 0,
        instructor: "Srijata Dey",
        remarks: "Absolutely avoid",
        type: "tutorial",
      },
      {
        section: "T14",
        room: "6108",
        days: "Th",
        hours: "1",
        rating: 9,
        instructor: "Rishikesh Vaidya",
        remarks: "Demi-God",
        type: "tutorial",
      },
      {
        section: "T15",
        room: "6101",
        days: "Th",
        hours: "1",
        rating: 8,
        instructor: "Debashis Bandyopadhyay",
        remarks: "Recommended",
        type: "tutorial",
      },
    ],
    labs: [
      {
        section: "P1",
        room: "2247",
        days: "F",
        hours: "1-2",
        rating: 0,
        instructor: "Srijata Dey",
        remarks: "Absolutely Avoid",
        type: "lab",
      },
      {
        section: "P2",
        room: "2247",
        days: "F",
        hours: "3-4",
        rating: 10,
        instructor: "Arpan Das",
        remarks: "God",
        type: "lab",
      },
      {
        section: "P3",
        room: "2247",
        days: "F",
        hours: "6-7",
        rating: 8,
        instructor: "Debi Datt Pant",
        remarks: "Recommended",
        type: "lab",
      },
      {
        section: "P4",
        room: "2247",
        days: "M",
        hours: "1-2",
        rating: 0,
        instructor: "Amol Holkundkar",
        remarks: "Unknown",
        type: "lab",
      },
      {
        section: "P5",
        room: "2247",
        days: "M",
        hours: "3-4",
        rating: 0,
        instructor: "Rajesh Chaoubisa",
        remarks: "Unknown",
        type: "lab",
      },
      {
        section: "P6",
        room: "2247",
        days: "M",
        hours: "6-7",
        rating: 9,
        instructor: "Sajal Mukherjee",
        remarks: "Recommended",
        type: "lab",
      },
      {
        section: "P7",
        room: "2247",
        days: "T",
        hours: "1-2",
        rating: 2,
        instructor: "Sandipan Dutta",
        remarks: "Avoid",
        type: "lab",
      },
      {
        section: "P8",
        room: "2247",
        days: "T",
        hours: "3-4",
        rating: 0,
        instructor: "Rajesh Chaoubisa",
        remarks: "Unknown",
        type: "lab",
      },
      {
        section: "P9",
        room: "2247",
        days: "T",
        hours: "6-7",
        rating: 9,
        instructor: "Biswanath Layek",
        remarks: "Recommended",
        type: "lab",
      },
      {
        section: "P10",
        room: "2247",
        days: "Th",
        hours: "1-2",
        rating: 7,
        instructor: "Bhavesh Chauhan",
        remarks: "Decent",
        type: "lab",
      },
      {
        section: "P11",
        room: "2247",
        days: "Th",
        hours: "3-4",
        rating: 0,
        instructor: "Srijata Dey",
        remarks: "Absolutely Avoid",
        type: "lab",
      },
      {
        section: "P12",
        room: "2247",
        days: "Th",
        hours: "6-7",
        rating: 7,
        instructor: "Bhavesh Chauhan",
        remarks: "Decent",
        type: "lab",
      },
      {
        section: "P13",
        room: "2247",
        days: "W",
        hours: "1-2",
        rating: 9,
        instructor: "Vaidya Rishikesh D",
        remarks: "Recommended",
        type: "lab",
      },
      {
        section: "P14",
        room: "2247",
        days: "W",
        hours: "3-4",
        rating: 9,
        instructor: "Madhukar Mishra",
        remarks: "Recommended",
        type: "lab",
      },
      {
        section: "P15",
        room: "2247",
        days: "W",
        hours: "6-7",
        rating: 8,
        instructor: "Biswanath Layek",
        remarks: "Recommended",
        type: "lab",
      },
    ],
  },
  {
    id: "bio",
    name: "Intro to Bio Science",
    code: "BIO101",
    group: "B",
    lectures: [
      {
        section: "L1",
        room: "5102",
        days: "M W",
        hours: "2,2",
        rating: 0,
        instructor: "Prabhat Nath Jha Shilpi Garg",
        remarks: "Both same",
        type: "lecture",
      },
      {
        section: "L2",
        room: "5102",
        days: "M W",
        hours: "4,4",
        rating: 0,
        instructor: "Prabhat Nath Jha, Shilpi Garg",
        remarks: "Both same",
        type: "lecture",
      },
    ],
    tutorials: [
      {
        section: "T1",
        room: "6154",
        days: "F",
        hours: "1",
        rating: 2,
        instructor: "Shashi Prakash Singh",
        remarks: "Avoid",
        type: "tutorial",
      },
      {
        section: "T2",
        room: "6157",
        days: "F",
        hours: "1",
        rating: 0,
        instructor: "Sushmita Basu",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T3",
        room: "6108",
        days: "F",
        hours: "1",
        rating: 0,
        instructor: "Meghana Tare",
        remarks: "Avoid at any cost",
        type: "tutorial",
      },
      {
        section: "T4",
        room: "6158",
        days: "F",
        hours: "1",
        rating: 8,
        instructor: "Shilpi Garg",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T5",
        room: "6159",
        days: "F",
        hours: "1",
        rating: 1,
        instructor: "B Vani",
        remarks: "Avoid",
        type: "tutorial",
      },
      {
        section: "T6",
        room: "6160",
        days: "F",
        hours: "1",
        rating: 0,
        instructor: "P. Yadukrishnan",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T7",
        room: "6161",
        days: "F",
        hours: "1",
        rating: 7.5,
        instructor: "Jitendra Panwar",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T8",
        room: "6153",
        days: "T",
        hours: "7",
        rating: 0,
        instructor: "Sushmita Basu",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T9",
        room: "6156",
        days: "T",
        hours: "8",
        rating: 1,
        instructor: "B Vani",
        remarks: "Avoid",
        type: "tutorial",
      },
      {
        section: "T10",
        room: "6158",
        days: "T",
        hours: "9",
        rating: 8,
        instructor: "Mukul Joshi",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T11",
        room: "6159",
        days: "T",
        hours: "9",
        rating: 0,
        instructor: "Jigneshkumar Dahyabhai",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T12",
        room: "6102",
        days: "T",
        hours: "9",
        rating: 9,
        instructor: "Prabhat Nath Jha",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T13",
        room: "6160",
        days: "T",
        hours: "9",
        rating: 7.5,
        instructor: "Jitendra Panwar",
        remarks: "Recommended",
        type: "tutorial",
      },
    ],
    labs: [
      {
        section: "P1",
        room: "2217",
        days: "F",
        hours: "1-2",
        rating: 0,
        instructor: "Vishal Saxena",
        remarks: "Avoid",
        type: "lab",
      },
      {
        section: "P2",
        room: "2217",
        days: "F",
        hours: "3-4",
        rating: 2,
        instructor: "Shibasish Chowdhury",
        remarks: "Avoid",
        type: "lab",
      },
      {
        section: "P3",
        room: "2217",
        days: "F",
        hours: "6-7",
        rating: 0,
        instructor: "Abha Gupta (RS)",
        remarks: "Unknown",
        type: "lab",
      },
      {
        section: "P4",
        room: "2217",
        days: "M",
        hours: "1-2",
        rating: 0,
        instructor: "Sudeshna Mukherjee",
        remarks: "Absolutely Avoid",
        type: "lab",
      },
      {
        section: "P5",
        room: "2217",
        days: "M",
        hours: "3-4",
        rating: 0,
        instructor: "Mukul Srivastava (RS)",
        remarks: "Unknown",
        type: "lab",
      },
      {
        section: "P6",
        room: "2217",
        days: "M",
        hours: "6-7",
        rating: 0,
        instructor: "Viraaj Kumar (RS)",
        remarks: "Unknown",
        type: "lab",
      },
      {
        section: "P7",
        room: "2217",
        days: "T",
        hours: "1-2",
        rating: 0,
        instructor: "Himanshi Kumari (RS)",
        remarks: "Unknown",
        type: "lab",
      },
      {
        section: "P8",
        room: "2217",
        days: "T",
        hours: "3-4",
        rating: 0,
        instructor: "Satya Omprabha (RS)",
        remarks: "Unknown",
        type: "lab",
      },
      {
        section: "P9",
        room: "2217",
        days: "T",
        hours: "6-7",
        rating: 0,
        instructor: "Charudutt Poonia (RS)",
        remarks: "Unknown",
        type: "lab",
      },
      {
        section: "P10",
        room: "2217",
        days: "Th",
        hours: "3-4",
        rating: 0,
        instructor: "Syamantak Majumder",
        remarks: "Unknown",
        type: "lab",
      },
      {
        section: "P11",
        room: "2217",
        days: "Th",
        hours: "6-7",
        rating: 0,
        instructor: "Mohit Rana (RS)",
        remarks: "Unknown",
        type: "lab",
      },
      {
        section: "P12",
        room: "2217",
        days: "W",
        hours: "1-2",
        rating: 0,
        instructor: "Mohit Gupta (RS)",
        remarks: "Unknown",
        type: "lab",
      },
      {
        section: "P13",
        room: "2217",
        days: "W",
        hours: "6-7",
        rating: 0,
        instructor: "Gitika Sharma (RS)",
        remarks: "Unknown",
        type: "lab",
      }
    ],
  },
  {
    id: "cp",
    name: "Computer Programming",
    code: "CP101",
    group: "B",
    lectures: [
      {
        section: "L1",
        room: "5102",
        days: "M W Th",
        hours: "3,3,9",
        rating: 9,
        instructor: "Bharat Richhariya",
        remarks: "Better for lectures",
        type: "lecture",
      },
      {
        section: "L2",
        room: "5102",
        days: "T Th F",
        hours: "2,2,2",
        rating: 7,
        instructor: "Jagat Sesh Challa",
        remarks: "Decent",
        type: "lecture",
      },
    ],
    tutorials: [],
    labs: [
      {
        section: "P1",
        room: "6114",
        days: "F",
        hours: "3-4",
        rating: 0,
        instructor: "Neha Sangwan (RS)",
        remarks: "Unknown",
        type: "lab",
      },
      {
        section: "P2",
        room: "6119",
        days: "F",
        hours: "6-7",
        rating: 0,
        instructor: "Radhika Bohra (RS)",
        remarks: "Unknown",
        type: "lab",
      },
      {
        section: "P3",
        room: "6114",
        days: "F",
        hours: "6-7",
        rating: 0,
        instructor: "Abhinand P. (RS)",
        remarks: "Unknown",
        type: "lab",
      },
      {
        section: "P4",
        room: "6116",
        days: "F",
        hours: "6-7",
        rating: 0,
        instructor: "Manasvi Singh (RS)",
        remarks: "Unknown",
        type: "lab",
      },
      {
        section: "P5",
        room: "6013",
        days: "F",
        hours: "6-7",
        rating: 0,
        instructor: "Mohit (RS)",
        remarks: "Unknown",
        type: "lab",
      },
      {
        section: "P6",
        room: "6114",
        days: "S",
        hours: "1-2",
        rating: 0,
        instructor: "Mohit (RS)",
        remarks: "Unknown",
        type: "lab",
      },
      {
        section: "P7",
        room: "6116",
        days: "M",
        hours: "6-7",
        rating: 0,
        instructor: "Ashin Babu (RS)",
        remarks: "Unknown",
        type: "lab",
      },
      {
        section: "P8",
        room: "6114",
        days: "T",
        hours: "3-4",
        rating: 0,
        instructor: "Sundaresan Raman",
        remarks: "Unknown",
        type: "lab",
      },
      {
        section: "P9",
        room: "6116",
        days: "T",
        hours: "3-4",
        rating: 0,
        instructor: "Ashin Babu (RS)",
        remarks: "Unknown",
        type: "lab",
      },
      {
        section: "P10",
        room: "6018",
        days: "Th",
        hours: "3-4",
        rating: 0,
        instructor: "Manasvi Singh (RS)",
        remarks: "Unknown",
        type: "lab",
      },
      {
        section: "P11",
        room: "6018",
        days: "W",
        hours: "3-4",
        rating: 0,
        instructor: "Neha Sangwan (RS)",
        remarks: "Unknown",
        type: "lab",
      },
      {
        section: "P12",
        room: "6019",
        days: "W",
        hours: "3-4",
        rating: 0,
        instructor: "To Be Announced",
        remarks: "Unknown",
        type: "lab",
      },
      {
        section: "P13",
        room: "6114",
        days: "W",
        hours: "6-7",
        rating: 0,
        instructor: "Radhika Bohra (RS)",
        remarks: "Unknown",
        type: "lab",
      },
      {
        section: "P14",
        room: "6116",
        days: "W",
        hours: "6-7",
        rating: 0,
        instructor: "Abhinand P. (RS)",
        remarks: "Unknown",
        type: "lab",
      },
      {
        section: "P15",
        room: "6017",
        days: "Th",
        hours: "3-4",
        rating: 0,
        instructor: "To Be Announced",
        remarks: "Unknown",
        type: "lab",
      },
    ],
  },
  {
    id: "trw",
    name: "Technical Report Writing",
    code: "TRW101",
    group: "B",
    lectures: [
      {
        section: "All",
        room: "TBA",
        days: "TBA",
        hours: "TBA",
        rating: 0,
        instructor: "TBA",
        remarks: "TBA",
        type: "lecture",
      },
    ],
    tutorials: [],
    labs: [],
  },
  {
    id: "lacv",
    name: "Linear Algebra and Complex Variable",
    code: "MATH101",
    group: "common",
    lectures: [
      {
        section: "L1",
        room: "5105",
        days: "M W Th",
        hours: "6,6,8",
        rating: 5,
        instructor: "Krishnendra Shekhawat / Balram Dubey",
        remarks: "Mediocre",
        type: "lecture",
      },
      {
        section: "L2",
        room: "5105",
        days: "T Th F",
        hours: "3,3,3",
        rating: 6,
        instructor: "Sangita Yadav / Trilok Mathur",
        remarks: "Mediocre",
        type: "lecture",
      },
      {
        section: "L3",
        room: "5105",
        days: "Various",
        hours: "Various",
        rating: 9,
        instructor: "Jitender Kumar / Gaurav Dwivedi",
        remarks: "Best",
        type: "lecture",
      },
    ],
    tutorials: [
      {
        section: "T1",
        room: "6164",
        days: "M",
        hours: "1",
        rating: 8.5,
        instructor: "Ashish Tiwari",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T2",
        room: "6154",
        days: "M",
        hours: "1",
        rating: 7.5,
        instructor: "Shuchita Goyal",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T3",
        room: "6157",
        days: "M",
        hours: "1",
        rating: 0,
        instructor: "Sudarshan Santra",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T4",
        room: "6158",
        days: "M",
        hours: "1",
        rating: 8.5,
        instructor: "Rahul Kumar",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T5",
        room: "6159",
        days: "M",
        hours: "1",
        rating: 9,
        instructor: "Jitender Kumar",
        remarks: "Highly Recommended",
        type: "tutorial",
      },
      {
        section: "T6",
        room: "6160",
        days: "M",
        hours: "1",
        rating: 6,
        instructor: "Krishnendra Shekhawat",
        remarks: "Decent",
        type: "tutorial",
      },
      {
        section: "T7",
        room: "6157",
        days: "T",
        hours: "1",
        rating: 8,
        instructor: "Biswanath Layek",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T8",
        room: "6158",
        days: "T",
        hours: "1",
        rating: 7,
        instructor: "Shailesh Trivedi",
        remarks: "Decent",
        type: "tutorial",
      },
      {
        section: "T9",
        room: "6159",
        days: "T",
        hours: "1",
        rating: 0,
        instructor: "Dhiraj Kumar Das",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T10",
        room: "6160",
        days: "T",
        hours: "1",
        rating: 0,
        instructor: "Rijubrata Kundu",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T11",
        room: "6161",
        days: "T",
        hours: "1",
        rating: 8.5,
        instructor: "Rahul Kumar",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T12",
        room: "6153",
        days: "Th",
        hours: "8",
        rating: 9,
        instructor: "Jitender Kumar",
        remarks: "Highly Recommended",
        type: "tutorial",
      },
      {
        section: "T13",
        room: "6154",
        days: "Th",
        hours: "8",
        rating: 0,
        instructor: "Dhiraj Kumar Das",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T14",
        room: "6103",
        days: "Th",
        hours: "8",
        rating: 8,
        instructor: "Gaurav Dwivedi",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T15",
        room: "6157",
        days: "Th",
        hours: "8",
        rating: 8,
        instructor: "Biswanath Layek",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T16",
        room: "6158",
        days: "Th",
        hours: "8",
        rating: 7.5,
        instructor: "Shuchita Goyal",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T17",
        room: "6157",
        days: "W",
        hours: "8",
        rating: 0,
        instructor: "Sudarshan Santra",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T18",
        room: "6158",
        days: "W",
        hours: "8",
        rating: 7,
        instructor: "Shailesh Trivedi",
        remarks: "Decent",
        type: "tutorial",
      },
      {
        section: "T19",
        room: "6159",
        days: "W",
        hours: "8",
        rating: 0,
        instructor: "Rijubrata Kundu",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T20",
        room: "6160",
        days: "W",
        hours: "8",
        rating: 10,
        instructor: "Arpan Das",
        remarks: "God",
        type: "tutorial",
      },
      {
        section: "T21",
        room: "6161",
        days: "W",
        hours: "8",
        rating: 8.5,
        instructor: "Rahul Kumar",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T22",
        room: "6162",
        days: "W",
        hours: "8",
        rating: 6,
        instructor: "Krishnendra Shekhawat",
        remarks: "Decent",
        type: "tutorial",
      },
      {
        section: "T23",
        room: "6103",
        days: "W",
        hours: "8",
        rating: 0,
        instructor: "Dhiraj Kumar Das",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T24",
        room: "1232",
        days: "W",
        hours: "8",
        rating: 8,
        instructor: "Gaurav Dwivedi",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T25",
        room: "1202",
        days: "W",
        hours: "8",
        rating: 7.5,
        instructor: "Shuchita Goyal",
        remarks: "Recommended",
        type: "tutorial",
      },
    ],
    labs: [],
  },
  {
    id: "prob",
    name: "Probability And Statistics",
    code: "MATH102",
    group: "common",
    lectures: [
      {
        section: "L1",
        room: "5102",
        days: "M W Th",
        hours: "6,6,8",
        rating: 4,
        instructor: "Rajesh Kumar / Divyum Sharma",
        remarks: "Absolutely Avoid",
        type: "lecture",
      },
      {
        section: "L2",
        room: "5102",
        days: "T Th F",
        hours: "3,3,3",
        rating: 7,
        instructor: "Pramod Eyyunni / Shivi Agarwal",
        remarks: "Decent",
        type: "lecture",
      },
      {
        section: "L3",
        room: "5105",
        days: "T Th F",
        hours: "6,6,6",
        rating: 9,
        instructor: "Anirudh Singh Rana / Sumanta Padsari",
        remarks: "Best",
        type: "lecture",
      },
    ],
    tutorials: [
      {
        section: "T1",
        room: "6103",
        days: "M",
        hours: "8",
        rating: 1,
        instructor: "Rakhee",
        remarks: "Avoid",
        type: "tutorial",
      },
      {
        section: "T2",
        room: "6154",
        days: "M",
        hours: "8",
        rating: 0,
        instructor: "Rijubrata Kundu",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T3",
        room: "6159",
        days: "M",
        hours: "8",
        rating: 0,
        instructor: "Sudarshan Santra",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T4",
        room: "6163",
        days: "M",
        hours: "8",
        rating: 0,
        instructor: "Dhiraj Kumar Das",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T5",
        room: "6160",
        days: "M",
        hours: "8",
        rating: 2,
        instructor: "Divyum Sharma",
        remarks: "Avoid",
        type: "tutorial",
      },
      {
        section: "T6",
        room: "6161",
        days: "M",
        hours: "8",
        rating: 8.5,
        instructor: "Rahul Kumar",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T7",
        room: "6162",
        days: "T",
        hours: "1",
        rating: 2,
        instructor: "Chandra Shekhar",
        remarks: "Avoid",
        type: "tutorial",
      },
      {
        section: "T8",
        room: "6163",
        days: "T",
        hours: "8",
        rating: 0,
        instructor: "Rijubrata Kundu",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T9",
        room: "6103",
        days: "T",
        hours: "8",
        rating: 2,
        instructor: "Shivi Agarwal",
        remarks: "Avoid",
        type: "tutorial",
      },
      {
        section: "T10",
        room: "6154",
        days: "T",
        hours: "8",
        rating: 7.5,
        instructor: "Shuchita Goyal",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T11",
        room: "6157",
        days: "T",
        hours: "8",
        rating: 0,
        instructor: "Sudarshan Santra",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T12",
        room: "6158",
        days: "T",
        hours: "8",
        rating: 0,
        instructor: "Dhiraj Kumar Das",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T13",
        room: "6159",
        days: "T",
        hours: "8",
        rating: 8.5,
        instructor: "Rahul Kumar",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T14",
        room: "6103",
        days: "Th",
        hours: "1",
        rating: 1,
        instructor: "Rakhee",
        remarks: "Avoid",
        type: "tutorial",
      },
      {
        section: "T15",
        room: "6154",
        days: "Th",
        hours: "1",
        rating: 7.5,
        instructor: "Shuchita Goyal",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T16",
        room: "6156",
        days: "Th",
        hours: "1",
        rating: 7.5,
        instructor: "Sumanta Pasari",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T17",
        room: "6157",
        days: "Th",
        hours: "1",
        rating: 0,
        instructor: "Rijubrata Kundu",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T18",
        room: "6158",
        days: "Th",
        hours: "1",
        rating: 0,
        instructor: "Sudarshan Santra",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T19",
        room: "6159",
        days: "Th",
        hours: "1",
        rating: 0,
        instructor: "Dhiraj Kumar Das",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T20",
        room: "6160",
        days: "Th",
        hours: "1",
        rating: 8.5,
        instructor: "Pramod Eyyunni",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T21",
        room: "6154",
        days: "W",
        hours: "1",
        rating: 9,
        instructor: "Anirudh Singh Rana",
        remarks: "Highly Recommended",
        type: "tutorial",
      },
      {
        section: "T22",
        room: "6157",
        days: "W",
        hours: "1",
        rating: 8.5,
        instructor: "Rahul Kumar",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T23",
        room: "6103",
        days: "W",
        hours: "1",
        rating: 1,
        instructor: "Rakhee",
        remarks: "Avoid",
        type: "tutorial",
      },
      {
        section: "T24",
        room: "6158",
        days: "W",
        hours: "1",
        rating: 0,
        instructor: "Rijubrata Kundu",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T25",
        room: "6159",
        days: "W",
        hours: "1",
        rating: 7.5,
        instructor: "Shuchita Goyal",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T26",
        room: "6160",
        days: "W",
        hours: "1",
        rating: 0,
        instructor: "Sudarshan Santra",
        remarks: "Unknown",
        type: "tutorial",
      },
    ],
    labs: [],
  },
  {
    id: "idt",
    name: "Innovation And Design Thinking",
    code: "IDE101",
    group: "common",
    lectures: [
      {
        section: "L1",
        room: "5102",
        days: "T",
        hours: "7",
        rating: 0,
        instructor: "Jyoti",
        remarks: "New (1 credit)",
        type: "lecture",
      },
      {
        section: "L2",
        room: "5102",
        days: "F",
        hours: "8",
        rating: 0,
        instructor: "Leela Rani",
        remarks: "New (1 credit)",
        type: "lecture",
      },
      {
        section: "L3",
        room: "2102",
        days: "T",
        hours: "8",
        rating: 0,
        instructor: "Arya Kumar",
        remarks: "New (1 credit)",
        type: "lecture",
      },
    ],
    tutorials: [
      {
        section: "T1",
        room: "1201",
        days: "Th",
        hours: "1",
        rating: 0,
        instructor: "Shriya Raina",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T2",
        room: "1202",
        days: "Th",
        hours: "1",
        rating: 0,
        instructor: "Sanchari Thakur",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T3",
        room: "1204",
        days: "Th",
        hours: "1",
        rating: 0,
        instructor: "Muthukumar G",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T4",
        room: "1205",
        days: "Th",
        hours: "1",
        rating: 3,
        instructor: "Prashant Uday Manohar",
        remarks: "Avoid (PUMA)",
        type: "tutorial",
      },
      {
        section: "T5",
        room: "1226",
        days: "Th",
        hours: "1",
        rating: 0,
        instructor: "Jayashree Mahesh",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T6",
        room: "1227",
        days: "Th",
        hours: "1",
        rating: 0,
        instructor: "Moammad Faraz Naim",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T7",
        room: "1233",
        days: "Th",
        hours: "1",
        rating: 0,
        instructor: "Jyoti",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T8",
        room: "2203",
        days: "M",
        hours: "1",
        rating: 0,
        instructor: "Jayashree Mahesh",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T9",
        room: "1201",
        days: "M",
        hours: "1",
        rating: 0,
        instructor: "Moammad Faraz Naim",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T10",
        room: "1233",
        days: "M",
        hours: "1",
        rating: 0,
        instructor: "Nirankush Dutta",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T11",
        room: "1234",
        days: "M",
        hours: "1",
        rating: 0,
        instructor: "Aneesh A M",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T12",
        room: "2204",
        days: "M",
        hours: "1",
        rating: 0,
        instructor: "Deepak Chitkara",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T13",
        room: "1227",
        days: "M",
        hours: "1",
        rating: 0,
        instructor: "Aniruddha Roy",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T14",
        room: "5101",
        days: "M",
        hours: "1",
        rating: 10,
        instructor: "Arpan Das",
        remarks: "God",
        type: "tutorial",
      },
      {
        section: "T15",
        room: "5102",
        days: "M",
        hours: "1",
        rating: 0,
        instructor: "Rakhi Agrawal",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T16",
        room: "6160",
        days: "T",
        hours: "8",
        rating: 0,
        instructor: "Moammad Faraz Naim",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T17",
        room: "6161",
        days: "T",
        hours: "8",
        rating: 0,
        instructor: "Nirankush Dutta",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T18",
        room: "1219",
        days: "T",
        hours: "8",
        rating: 0,
        instructor: "Faizan Mohammad Rashid",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T19",
        room: "6162",
        days: "T",
        hours: "8",
        rating: 8,
        instructor: "Aritra Banerjee",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T20",
        room: "6152",
        days: "T",
        hours: "8",
        rating: 0,
        instructor: "Shriya Raina",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T21",
        room: "1220",
        days: "T",
        hours: "8",
        rating: 8.5,
        instructor: "Sharda Tripathi",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T22",
        room: "1222",
        days: "T",
        hours: "8",
        rating: 0,
        instructor: "Vinay Chamola",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T23",
        room: "6159",
        days: "Th",
        hours: "8",
        rating: 3,
        instructor: "Prashant Uday Manohar",
        remarks: "Avoid (PUMA)",
        type: "tutorial",
      },
      {
        section: "T24",
        room: "1219",
        days: "Th",
        hours: "8",
        rating: 0,
        instructor: "Faizan Mohammad Rashid",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T25",
        room: "6160",
        days: "Th",
        hours: "8",
        rating: 8,
        instructor: "Aritra Banerjee",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T26",
        room: "6161",
        days: "Th",
        hours: "8",
        rating: 10,
        instructor: "Arpan Das",
        remarks: "God",
        type: "tutorial",
      },
      {
        section: "T27",
        room: "1220",
        days: "Th",
        hours: "8",
        rating: 0,
        instructor: "Vinay Chamola",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T28",
        room: "6104",
        days: "Th",
        hours: "8",
        rating: 0,
        instructor: "Rakhi Agrawal",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T29",
        room: "6107",
        days: "Th",
        hours: "8",
        rating: 0,
        instructor: "Yash Sinha",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T30",
        room: "6162",
        days: "Th",
        hours: "8",
        rating: 7,
        instructor: "Partha Sartha Addy",
        remarks: "Decent",
        type: "tutorial",
      },
      {
        section: "T31",
        room: "6104",
        days: "W",
        hours: "1",
        rating: 0,
        instructor: "Yash Sinha",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T32",
        room: "1222",
        days: "W",
        hours: "1",
        rating: 0,
        instructor: "Sanchari Thakur",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T33",
        room: "1225",
        days: "W",
        hours: "1",
        rating: 0,
        instructor: "Muthukumar G",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T34",
        room: "6157",
        days: "W",
        hours: "7",
        rating: 7,
        instructor: "Partha Sartha Addy",
        remarks: "Decent",
        type: "tutorial",
      },
      {
        section: "T35",
        room: "1201",
        days: "W",
        hours: "1",
        rating: 0,
        instructor: "Aneesh A M",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T36",
        room: "6162",
        days: "W",
        hours: "1",
        rating: 0,
        instructor: "Deepak Chitkara",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T37",
        room: "6163",
        days: "W",
        hours: "1",
        rating: 0,
        instructor: "Aniruddha Roy",
        remarks: "Unknown",
        type: "tutorial",
      },
      {
        section: "T38",
        room: "1223",
        days: "W",
        hours: "1",
        rating: 8.5,
        instructor: "Sharda Tripathi",
        remarks: "Recommended",
        type: "tutorial",
      },
      {
        section: "T39",
        room: "6161",
        days: "W",
        hours: "1",
        rating: 0,
        instructor: "Jayashree Mahesh",
        remarks: "Unknown",
        type: "tutorial",
      },
    ],
    labs: [],
  },
]

// Helper to get courses by group
export function getCoursesByGroup(group: "A" | "B"): Course[] {
  return courses.filter((c) => c.group === group || c.group === "common")
}

// Helper to get all common courses
export function getCommonCourses(): Course[] {
  return courses.filter((c) => c.group === "common")
}
